### ISSUE TITLE
Scrollwheel no working anymore on google calendar with the "Sunrise for Google Calendar" addon

### ISSUE THREAD

**Issue by renanlecaro** [ellenli/sunrise#2]
I'm on chrome Version 55.0.2883.87 m (windows)

The scrollwheel doesn't work in any view with the addon active. 
My AdBlocker is disabled. 

Step to reproduce : open google calendar on windows with chrome latest version. Try to scroll the calendar vertically.

The scroll seems to work a few seconds when the page is loading. I suspect you used some "nicescroll" thing and it may be broken.

Nice UI though. But not usable for me as-is

**Comment by ellenli** [comment]
Thanks for logging this. 👍 

The issue has been fixed in https://github.com/ellenli/sunrise/commit/8ea11a13111fb4f8915f3d520ae3f4dcb6a3d609 (build 1.1.9). The update will be available in the Chrome Web Store within the next hour.
