### ISSUE TITLE
Text is hard to read on dark event blocks

### ISSUE THREAD

**Issue by ellenli** [ellenli/sunrise#4]
![image](https://cloud.githubusercontent.com/assets/933419/21820194/c0952c22-d73c-11e6-863e-522d48f7397f.png)

**Comment by AlexeiDarmin** [comment]
What if you made the text a semi-transparent black like `rgba(0,0,0,0.8)` (random example)

This would make it darker on dark surfaces and lighter on light surfaces

**Comment by ellenli** [comment]
It's already a semi-transparent black, and it isn't working too well. Making it a semi-transparent white won't work very well either:

![image](https://cloud.githubusercontent.com/assets/933419/21832462/50fd5c76-d779-11e6-908e-d5650f2831ba.png)

Wellllppp. I guess people can just...choose a lighter color.......
