### ISSUE TITLE
Make appointment slots UX great again

### ISSUE THREAD

**Issue by mariusbutuc** [ellenli/sunrise#7]
Using [Google Calendar appointment slots](https://support.google.com/calendar/answer/190998?hl=en&ref_topic=3417926) is a bit difficult in the current version.

### Before:

![planswell_-_calendar_-_week_of_jan_9__2017](https://cloud.githubusercontent.com/assets/511893/21935339/28755eda-d97b-11e6-8415-7e98b75a9dc1.png)

### After:

![planswell_-_calendar_-_week_of_jan_9__2017](https://cloud.githubusercontent.com/assets/511893/21935364/36db84f4-d97b-11e6-8aa2-69c6f40d9023.png)

**Comment by ellenli** [comment]
Fixed in bda6b84b973d0f5169bd253d380dfb4d69a58c6a.

Your version should automatically update in the next couple days (or you can re-install from the web store later today). Thanks for reporting the issue!

**Comment by mariusbutuc** [comment]
Awesome, it works great. 👍 

Thanks for the quick fix!
