### ISSUE TITLE
I can´t use it

### ISSUE THREAD

**Issue by fonzzzmg** [ellenli/sunrise#9]
no way I can enter in the config menu
![2017-03-13 19 21 51](https://cloud.githubusercontent.com/assets/26390850/23871504/a289e5d0-0822-11e7-84b1-d8ccb635f78d.jpg)

**Comment by ellenli** [comment]
There's no config menu. The extension is applied right away. Load up [your calendar](https://calendar.google.com/calendar) to see the changes.
